# Change these first
owner: grizak       # Your GitHub username, where this repository lives
repo: upptime        # Your Upptime repo name

sites:
  - name: Finance Tracker
    url: https://financetracker.isaksweb.xyz
  - name: Cloudflare DNS
    url: 1.1.1.1

status-website:
  cname: status.isaksweb.xyz
  logoUrl: https://raw.githubusercontent.com/grizak/upptime/master/assets/upptime-icon.svg # optional, replace with your own logo if you like
  name: "Isak's Web Status"
  introTitle: "Welcome to **Isak’s Web Status**"
  introMessage: "This is the real-time status page for my websites and services. All data is powered by GitHub Actions — no server required."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/grizak/upptime

# Optional cosmetic theme settings
theme:
  primary: "#1affff"
  success: "#28a745"
  warning: "#ffc107"
  danger: "#dc3545"

# Optional footer
footer: "© 2025 Isak Grönlund – All rights reserved."

# Uptime checks
interval: 5            # check every 5 minutes
retry-interval: 2      # retry 2 minutes if failed
max-retries: 2

# Timezone for displaying times
timezone: "Europe/Stockholm"

notifications:
  email:
    - to: "you@yourdomain.com"      # who receives the email
      from: "status@isaksweb.xyz"  # your Zoho email
      subject: "[STATUS] {{site.name}} is {{status}}"
      smtp:
        host: "smtp.zoho.com"
        port: 587
        secure: false               # false for TLS, true if using port 465 SSL
        auth:
          user: ${{ secrets.ZOHO_EMAIL }}
          pass: ${{ secrets.ZOHO_PASS }}
